package internalFrames;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import proyectofinal.Usuario;
import proyectofinal.frmUsuario;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author lcarv
 */
public class ifrmUsuarioDel extends javax.swing.JInternalFrame {

    frmUsuario usuarioVentana;
    Usuario userList;
    
    public ifrmUsuarioDel(frmUsuario usuarioVentana, Usuario userList) {
        initComponents();
        this.usuarioVentana = usuarioVentana;
        this.usuarioVentana = usuarioVentana;
        this.userList = userList;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupAdmin = new javax.swing.ButtonGroup();
        btnGrupEstado = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        cbxBoxUsers = new javax.swing.JComboBox<>();
        btnDel = new javax.swing.JButton();
        lblcontraseña = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();

        setClosable(true);

        lblTitle.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Modificar usuarios");

        lblUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Nombre de Usuario:");

        cbxBoxUsers.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbxBoxUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un usuario." }));
        cbxBoxUsers.setToolTipText("Selecciona un usuario");
        cbxBoxUsers.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                cbxBoxUsersPopupMenuWillBecomeVisible(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnDel.setText("Eliminar");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        lblcontraseña.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblcontraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcontraseña.setText("Contraseña actual:");

        txtPass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPass.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblcontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxBoxUsers, 0, 230, Short.MAX_VALUE)
                            .addComponent(txtPass))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(cbxBoxUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontraseña)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int modificar = JOptionPane.showConfirmDialog(this, "Esta seguro de continuar", "Confirmación",JOptionPane.YES_NO_OPTION);
        if (modificar == JOptionPane.YES_OPTION) {
            int idUser = (int)cbxBoxUsers.getSelectedIndex();
            String user = (String) cbxBoxUsers.getSelectedItem();
            String passActual = txtPass.getText();
            if (passActual.equals(userList.users[idUser].getContrasena())) {
                userList.deleteUser(idUser + 1);
                JOptionPane.showMessageDialog(this, "Usuario "+user+" modificado con exito.", "Modificado", JOptionPane.INFORMATION_MESSAGE);
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "contraseña actual incorrecta.", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtPass.requestFocus();
            }
        } else {
            clear();
        }
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void cbxBoxUsersPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbxBoxUsersPopupMenuWillBecomeVisible
        String users[] = new String[userList.idUsers+1];
        DefaultComboBoxModel<String> modelUsers = new DefaultComboBoxModel<String>();
        for (int i = 0; i < userList.idUsers; i++) {
            users[i] = userList.users[i].getNombre();
            modelUsers.addElement(users[i]);
        }
        cbxBoxUsers.setModel(modelUsers);
        txtPass.setEnabled(true);
    }//GEN-LAST:event_cbxBoxUsersPopupMenuWillBecomeVisible

    public void clear(){
        DefaultComboBoxModel<String> modelUsers = new DefaultComboBoxModel<String>();
        modelUsers.addElement("Seleccione un usuario.");
        cbxBoxUsers.setModel(modelUsers);
        txtPass.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.ButtonGroup btnGrupAdmin;
    private javax.swing.ButtonGroup btnGrupEstado;
    private javax.swing.JComboBox<String> cbxBoxUsers;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
