package internalFrames;

import javax.swing.JOptionPane;
import proyectofinal.Usuario;
import proyectofinal.frmUsuario;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author lcarv
 */
public class ifrmUsuarioAdd extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmUsuarioAdd
     */
    frmUsuario usuarioVentana;
    Usuario userList;
    
    public ifrmUsuarioAdd(frmUsuario usuarioVentana, Usuario userList) {
        initComponents();
        this.usuarioVentana = usuarioVentana;
        this.userList = userList;
        
        for (int i = 0; i < userList.idUsers; i++) {
            System.out.println(userList.users[i].getNombre() + " id: " + userList.users[i].getRegistro());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupNivel = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        lblAcceso = new javax.swing.JLabel();
        rbtCajero = new javax.swing.JRadioButton();
        rbtAdmin = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agregar usuarios");

        lblTitle.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Agregar Usuarios");

        lblNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblNombre.setText("Nombre de Usuario:");

        lblContraseña.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblContraseña.setText("Contraseña:");

        txtPass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lblAcceso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblAcceso.setText("Nivel de Acceso: ");

        btnGrupNivel.add(rbtCajero);
        rbtCajero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtCajero.setSelected(true);
        rbtCajero.setText("Cajero.");

        btnGrupNivel.add(rbtAdmin);
        rbtAdmin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtAdmin.setText("Administrador.");

        btnAgregar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtCajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtAdmin)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcceso)
                    .addComponent(rbtCajero)
                    .addComponent(rbtAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!txtUsuario.getText().isEmpty() && !txtPass.getText().isEmpty()) {
            int registro = userList.idUsers;
            System.out.println("registro: " + registro);
            String nombre = txtUsuario.getText();
            String pass = txtPass.getText();
            boolean admin = false;
            if (rbtCajero.isSelected()) {
                admin = false;
            }
            if (rbtAdmin.isSelected()) {
                admin = true;
            }
            userList.add(registro + 1, nombre, pass, admin, true);
            JOptionPane.showMessageDialog(this, "Usuario "+userList.users[registro].getNombre()+" Registrado con exito.", "Registrado", JOptionPane.INFORMATION_MESSAGE);
            clear();
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese todos los datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtUsuario.requestFocus();
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    public void clear(){
        txtPass.setText("");
        txtUsuario.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup btnGrupNivel;
    private javax.swing.JLabel lblAcceso;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtAdmin;
    private javax.swing.JRadioButton rbtCajero;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
