/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectofinal;

import datosCaja.Ventas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macha
 */
public class dlgVentas extends javax.swing.JDialog {

    /**
     * Creates new form dlgVentas
     */
    Ventas ventasList;
    int cantPedidos, indexPed;
    
    public dlgVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public dlgVentas(java.awt.Frame parent, boolean modal, Ventas ventasList) {
        super(parent, modal);
        initComponents();
        indexPed = 1;
        this.ventasList = ventasList;
        this.cantPedidos = this.ventasList.getIdPedido();
        ventasList(indexPed);
        if (this.cantPedidos == 1) {
            btnNext.setEnabled(false);
        }
    }

    public void ventasList(int idPedido){
        if (this.cantPedidos != 0) {
            idPedido--;
            DefaultTableModel modelo = new DefaultTableModel();
            String[] cabecera = {"Producto", "Cantidad", "Precio", "Total"};
            modelo.setColumnIdentifiers(cabecera);

            String nombreProduct[] = new String[this.ventasList.getIdPedido() + 1];
            float precioProduct[] = new float[this.ventasList.getIdPedido() + 1];
            int cantProduct[] = new int[this.ventasList.getIdPedido() + 1];
            float total;

            nombreProduct = this.ventasList.ventasList[idPedido].getProductos();
            precioProduct = this.ventasList.ventasList[idPedido].getPrecios();
            cantProduct = this.ventasList.ventasList[idPedido].getCantidades();
            total = this.ventasList.ventasList[idPedido].getTotal();

            Object[] datos = new Object[5];
            for (int j = 0; j < this.ventasList.ventasList[idPedido].getCantProducts(); j++) {
                System.out.println(j);
                datos [0] = nombreProduct[j];
                datos [1] = cantProduct[j];
                datos [2] = "$" + Float.toString(precioProduct[j]);
                if (j == this.ventasList.ventasList[idPedido].getCantProducts() - 1) {
                    datos [3] = "$" + Float.toString(total);
                }
                modelo.addRow(datos);
            }
            tblVentas.setModel(modelo);
            lblPedido.setText("Pedido: " + indexPed);
        } else {
            btnPrew.setEnabled(false);
            btnNext.setEnabled(false);
        }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnPrew = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblPedido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ventas");

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblVentas);

        btnPrew.setText("<-");
        btnPrew.setEnabled(false);
        btnPrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrewActionPerformed(evt);
            }
        });

        btnNext.setText("->");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        lblPedido.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblPedido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPedido.setText("Sin pedidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrew)
                        .addGap(18, 18, 18)
                        .addComponent(lblPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrew)
                    .addComponent(btnNext)
                    .addComponent(lblPedido))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrewActionPerformed
        indexPed--;
        ventasList(indexPed);
        if (indexPed == 1) {
            btnPrew.setEnabled(false);
            btnNext.setEnabled(true);
        } else {
            btnNext.setEnabled(true);
            btnPrew.setEnabled(true);
        }
        lblPedido.setText("Pedido: " + indexPed);
    }//GEN-LAST:event_btnPrewActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        indexPed++;
        ventasList(indexPed);
        if (indexPed == cantPedidos) {
            btnNext.setEnabled(false);
            btnPrew.setEnabled(true);
        } else {
            btnNext.setEnabled(true);
            btnPrew.setEnabled(true);
        }
        lblPedido.setText("Pedido: " + indexPed);
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgVentas dialog = new dlgVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
