/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import datosCaja.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author macha
 */
public class frmCaja extends javax.swing.JFrame {

    /**
     * Creates new form frmCaja
     */
    int xMouse, yMouse;
    String productoNombre[];
    int cant[];
    ArrayList<Integer> lisCantProduct = new ArrayList<>();
    ArrayList<Integer> listIdsProducts = new ArrayList<>();
    float precio[];
    int cantProducts = 0;
    float totalPagar = 0.0f;
    
    ColaPedido colaPedido = new ColaPedido();
    
    //datos del Main
    frmMain main;
    Producto productList;
    Ventas ventasList;
    
    public frmCaja() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public frmCaja(frmMain main, Producto productList, Ventas ventasList) {
        this.main = main;
        this.productList = productList;
        this.ventasList = ventasList;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        pnlPedido = new javax.swing.JPanel();
        pnlHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        pnlTblPedido = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        pnlCons = new javax.swing.JPanel();
        btnPagar1 = new javax.swing.JPanel();
        lblPagar1 = new javax.swing.JLabel();
        btnDemo1 = new javax.swing.JPanel();
        btnDemo2 = new javax.swing.JPanel();
        btnDemo3 = new javax.swing.JPanel();
        btnVentas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerPanel.setOpaque(false);
        headerPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerPanelMouseDragged(evt);
            }
        });
        headerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerPanelMousePressed(evt);
            }
        });

        lblExit.setBackground(new java.awt.Color(10, 70, 192));
        lblExit.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblExit.setForeground(new java.awt.Color(242, 242, 242));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblExitMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 730, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        pnlPedido.setBackground(new java.awt.Color(242, 242, 242));
        pnlPedido.setForeground(new java.awt.Color(242, 242, 242));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoh (1).png"))); // NOI18N

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });
        txtCodigoProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoProductoKeyTyped(evt);
            }
        });

        tblPedido.setBackground(new java.awt.Color(242, 242, 242));
        tblPedido.setForeground(new java.awt.Color(0, 0, 0));
        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblPedido.setEnabled(false);
        tblPedido.setFocusable(false);
        pnlTblPedido.setViewportView(tblPedido);

        javax.swing.GroupLayout pnlPedidoLayout = new javax.swing.GroupLayout(pnlPedido);
        pnlPedido.setLayout(pnlPedidoLayout);
        pnlPedidoLayout.setHorizontalGroup(
            pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlPedidoLayout.createSequentialGroup()
                        .addGroup(pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCodigoProducto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlTblPedido, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlPedidoLayout.setVerticalGroup(
            pnlPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTblPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 560));

        pnlCons.setBackground(new java.awt.Color(10, 70, 192));

        btnPagar1.setBackground(new java.awt.Color(255, 223, 48));
        btnPagar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagar1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPagar1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPagar1MouseReleased(evt);
            }
        });

        lblPagar1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblPagar1.setForeground(new java.awt.Color(242, 242, 242));
        lblPagar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPagar1.setText("PAGAR");

        javax.swing.GroupLayout btnPagar1Layout = new javax.swing.GroupLayout(btnPagar1);
        btnPagar1.setLayout(btnPagar1Layout);
        btnPagar1Layout.setHorizontalGroup(
            btnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPagar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPagar1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnPagar1Layout.setVerticalGroup(
            btnPagar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPagar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPagar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnDemo1.setBackground(new java.awt.Color(255, 223, 48));
        btnDemo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDemo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDemo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDemo1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDemo1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDemo1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnDemo1Layout = new javax.swing.GroupLayout(btnDemo1);
        btnDemo1.setLayout(btnDemo1Layout);
        btnDemo1Layout.setHorizontalGroup(
            btnDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btnDemo1Layout.setVerticalGroup(
            btnDemo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnDemo2.setBackground(new java.awt.Color(255, 223, 48));
        btnDemo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDemo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDemo2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDemo2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDemo2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDemo2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnDemo2Layout = new javax.swing.GroupLayout(btnDemo2);
        btnDemo2.setLayout(btnDemo2Layout);
        btnDemo2Layout.setHorizontalGroup(
            btnDemo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        btnDemo2Layout.setVerticalGroup(
            btnDemo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnDemo3.setBackground(new java.awt.Color(255, 223, 48));
        btnDemo3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDemo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDemo3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDemo3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDemo3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDemo3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btnDemo3Layout = new javax.swing.GroupLayout(btnDemo3);
        btnDemo3.setLayout(btnDemo3Layout);
        btnDemo3Layout.setHorizontalGroup(
            btnDemo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        btnDemo3Layout.setVerticalGroup(
            btnDemo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        btnVentas.setBackground(new java.awt.Color(255, 223, 48));
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVentasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVentasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVentasMouseReleased(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnVentas.png"))); // NOI18N

        javax.swing.GroupLayout btnVentasLayout = new javax.swing.GroupLayout(btnVentas);
        btnVentas.setLayout(btnVentasLayout);
        btnVentasLayout.setHorizontalGroup(
            btnVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnVentasLayout.setVerticalGroup(
            btnVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTotal.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(242, 242, 242));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("TOTAL: $0.0");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CAJA");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DEMO");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DEMO");

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DEMO");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VENTAS");

        javax.swing.GroupLayout pnlConsLayout = new javax.swing.GroupLayout(pnlCons);
        pnlCons.setLayout(pnlConsLayout);
        pnlConsLayout.setHorizontalGroup(
            pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(pnlConsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDemo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDemo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDemo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlConsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnPagar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlConsLayout.setVerticalGroup(
            pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsLayout.createSequentialGroup()
                        .addComponent(btnDemo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsLayout.createSequentialGroup()
                        .addComponent(btnDemo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)))
                .addGroup(pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDemo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addComponent(lblTotal)
                .addGap(78, 78, 78))
            .addGroup(pnlConsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsLayout.createSequentialGroup()
                    .addContainerGap(503, Short.MAX_VALUE)
                    .addComponent(btnPagar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        getContentPane().add(pnlCons, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 290, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setBackground(Color.red);
        lblExit.setForeground(new Color(242,242,242));
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setBackground(new Color(10,70,192));
        lblExit.setForeground(new Color(242,242,242));
    }//GEN-LAST:event_lblExitMouseExited

    private void lblExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMousePressed
        lblExit.setBackground(new Color(204, 0, 0));
    }//GEN-LAST:event_lblExitMousePressed

    private void lblExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON1) {
            dispose();
            main.setVisible(true);
            lblExit.setBackground(Color.red);
        }
    }//GEN-LAST:event_lblExitMouseReleased

    private void headerPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerPanelMouseDragged

    private void headerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerPanelMousePressed

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        if (txtCodigoProducto.getText().isEmpty()) {
            //Detecta si el txtCodigoProducto esta vacio.
            JOptionPane.showConfirmDialog(this, "Escane un producto.");
        } else {
            //calculamos la cantidad del producto segun el formato del txtCodigoProducto.
            int cantProductCalc = calcularCantProductos(txtCodigoProducto.getText());
            lisCantProduct.add(cantProductCalc);
            int productoCodigo = Integer.parseInt(txtCodigoProducto.getText());
            boolean productEncontrado = false; //Bandera para saber si se encontro el producto
            
            //Recorremos la lista de productos
            for (int i = 0; i < productList.cant; i++) {
                //comparamos el codigo con el codigo de la lista de producto por si coinciden
                if (productList.pro[i].id == productoCodigo) {
                    this.listIdsProducts.add(productoCodigo);
                    String producto = productList.pro[i].getNombre(); //extraemos el nombre del producto
                    float precio = productList.pro[i].getPrecio(); //extraemos el precio del producto
                    float pagarCant = 0.0f; //inicializamos el valor de la cantidad a pagar
                    colaPedido.Encolar(producto, precio, cantProductCalc); //Encolamos el producto en la colaPedido
                    productEncontrado = true; //Validamos que el producto fue encontrado

                    DefaultTableModel modelo = new DefaultTableModel();
                    String[] cabecera = {"Producto", "Cantidad", "Precio"};
                    modelo.setColumnIdentifiers(cabecera);

                    String nombreProduct[] = new String[this.colaPedido.cantNodos];
                    float precioProduct[] = new float[this.colaPedido.cantNodos];
                    int cantProduct[] = new int[this.colaPedido.cantNodos];

                    nombreProduct = this.colaPedido.imprimirNombre();
                    precioProduct = this.colaPedido.imprimirPrecio();
                    cantProduct = this.colaPedido.imprimirCant();
                    
                    Object[] datos = new Object[3];

                    for (int j = 0; j < this.colaPedido.cantNodos; j++) {
                        datos [0] = nombreProduct[j];
                        datos [1] = cantProduct[j];
                        datos [2] = "$" + Float.toString(precioProduct[j] * cantProduct[j]);
                        pagarCant += (precioProduct[j] * cantProduct[j]);
                        modelo.addRow(datos);
                    }
                    totalPagar = pagarCant; //pasamos el valor a la variable global totalPagar
                    lblTotal.setText("TOTAL: $"+ Float.toString(totalPagar));
                    tblPedido.setModel(modelo);
                    this.cantProducts++;
                    break; //interrumpimos el for
                }
            }
            if (!productEncontrado) {
                JOptionPane.showConfirmDialog(this, "Producto no encontrado.");
            }
            txtCodigoProducto.setText("");
        }
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtCodigoProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoProductoKeyTyped
        char c = evt.getKeyChar();

        // Acepta solo números y el signo de asterisco
        if (!Character.isDigit(c) && c != '*') {
            evt.consume(); // Elimina el carácter si no es un número o asterisco
        }
    }//GEN-LAST:event_txtCodigoProductoKeyTyped

    private void btnPagar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagar1MouseEntered
        btnPagar1.setBackground(new Color(246, 255, 48));
    }//GEN-LAST:event_btnPagar1MouseEntered

    private void btnPagar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagar1MouseExited
        btnPagar1.setBackground(new Color(255, 223, 48));
    }//GEN-LAST:event_btnPagar1MouseExited

    private void btnPagar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagar1MousePressed
        btnPagar1.setBackground(new Color(242, 211, 45));
    }//GEN-LAST:event_btnPagar1MousePressed

    private void btnPagar1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagar1MouseReleased
        btnPagar1.setBackground(new Color(255, 223, 48));
        
        System.out.println(this.listIdsProducts.get(0));
        
        for (int i = 0; i < this.listIdsProducts.size(); i++) {
            int newStock = this.lisCantProduct.get(i);
            int stock = this.productList.pro[this.listIdsProducts.get(i) - 1].getStock();
            newStock = stock - newStock;
            this.productList.pro[this.listIdsProducts.get(i) - 1].setStock(newStock);
            System.out.println("Stok: " + newStock);
        }
        
        String nombreProduct[] = new String[this.colaPedido.cantNodos + 1];
        float precioProduct[] = new float[this.colaPedido.cantNodos + 1];
        int cantProduct[] = new int[this.colaPedido.cantNodos + 1];
        
        nombreProduct = this.colaPedido.imprimirNombre();
        precioProduct = this.colaPedido.imprimirPrecio();
        cantProduct = this.colaPedido.imprimirCant();
        
        ventasList.add(nombreProduct, cantProduct, precioProduct, totalPagar, this.cantProducts);
        this.cantProducts = 0;
        
        colaPedido.limpiarDatos();
        colaPedido.RecorrerPila();
        DefaultTableModel modelo = new DefaultTableModel();
        String[] cabecera = {"Producto", "Cantidad", "Precio"};
        modelo.setColumnIdentifiers(cabecera);

        Object[] datos = new Object[3];
        totalPagar = 0.0f;
        lblTotal.setText("TOTAL: $"+ Float.toString(totalPagar));
        tblPedido.setModel(modelo);
    }//GEN-LAST:event_btnPagar1MouseReleased

    private void btnDemo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo1MouseEntered
        btnDemo1.setBackground(new Color(246, 255, 48));
    }//GEN-LAST:event_btnDemo1MouseEntered

    private void btnDemo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo1MouseExited
        btnDemo1.setBackground(new Color(255, 223, 48));
    }//GEN-LAST:event_btnDemo1MouseExited

    private void btnDemo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo1MousePressed
        btnDemo1.setBackground(new Color(242, 211, 45));
    }//GEN-LAST:event_btnDemo1MousePressed

    private void btnDemo1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo1MouseReleased
        btnDemo1.setBackground(new Color(255, 223, 48));
    }//GEN-LAST:event_btnDemo1MouseReleased

    private void btnDemo2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo2MouseEntered
        btnDemo2.setBackground(new Color(246, 255, 48));
    }//GEN-LAST:event_btnDemo2MouseEntered

    private void btnDemo2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo2MouseExited
        btnDemo2.setBackground(new Color(255, 223, 48));
    }//GEN-LAST:event_btnDemo2MouseExited

    private void btnDemo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo2MousePressed
        btnDemo2.setBackground(new Color(242, 211, 45));
    }//GEN-LAST:event_btnDemo2MousePressed

    private void btnDemo2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo2MouseReleased
        btnDemo2.setBackground(new Color(255, 223, 48));
    }//GEN-LAST:event_btnDemo2MouseReleased

    private void btnDemo3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo3MouseEntered
        btnDemo3.setBackground(new Color(246, 255, 48));
    }//GEN-LAST:event_btnDemo3MouseEntered

    private void btnDemo3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo3MouseExited
        btnDemo3.setBackground(new Color(255, 223, 48));
    }//GEN-LAST:event_btnDemo3MouseExited

    private void btnDemo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo3MousePressed
        btnDemo3.setBackground(new Color(242, 211, 45));
    }//GEN-LAST:event_btnDemo3MousePressed

    private void btnDemo3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDemo3MouseReleased
        btnDemo3.setBackground(new Color(255, 223, 48));
    }//GEN-LAST:event_btnDemo3MouseReleased

    private void btnVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseEntered
        btnVentas.setBackground(new Color(246, 255, 48));
    }//GEN-LAST:event_btnVentasMouseEntered

    private void btnVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseExited
        btnVentas.setBackground(new Color(255, 223, 48));
    }//GEN-LAST:event_btnVentasMouseExited

    private void btnVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMousePressed
        btnVentas.setBackground(new Color(242, 211, 45));
    }//GEN-LAST:event_btnVentasMousePressed

    private void btnVentasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentasMouseReleased
        btnVentas.setBackground(new Color(255, 223, 48));
        dlgVentas ventasWin = new dlgVentas(main, rootPaneCheckingEnabled, ventasList);
        ventasWin.setVisible(true);
    }//GEN-LAST:event_btnVentasMouseReleased

    public int calcularCantProductos(String input){
        if (input.contains("*")) {
            String[] partes = input.split("\\*");
            if (partes.length == 2) {
                try {
                    // Obtener la parte después del '*'
                    String resultado = partes[1].trim();
                    // Actualizar el JTextField
                    txtCodigoProducto.setText(resultado);
                    
                    int numero = Integer.parseInt(partes[0].trim());
                    // Puedes hacer lo que quieras con 'numero' aquí
                    
                    System.out.println("Numero de cantidad: " + numero + ".");
                    return numero;
                } catch (NumberFormatException ex) {
                    System.err.println("Error al convertir el número.");
                }
            } else {
                System.err.println("Formato incorrecto. Asegúrate de incluir solo un '*'.");
            }
        } else {
            System.err.println("No se encontró '*'.");
        }
        return 1;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnDemo1;
    private javax.swing.JPanel btnDemo2;
    private javax.swing.JPanel btnDemo3;
    private javax.swing.JPanel btnPagar1;
    private javax.swing.JPanel btnVentas;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblPagar1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlCons;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlPedido;
    private javax.swing.JScrollPane pnlTblPedido;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTextField txtCodigoProducto;
    // End of variables declaration//GEN-END:variables
}
