package proyectofinal;

import internalFrames.ifrmUsuarioAdd;
import internalFrames.ifrmUsuarioMod;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lcarv
 */
public class frmUsuario extends javax.swing.JFrame {
    frmMain main;
    Usuario userList;
    
    public frmUsuario() {
        initComponents();
    }
    public frmUsuario(frmMain main, Usuario userList) {
        initComponents();
        this.main = main;
        this.userList = userList;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeskUsuario = new javax.swing.JDesktopPane();
        MnuUsuarios = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MniUsuariosAdd = new javax.swing.JMenuItem();
        MniUsuariosMod = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MniRegresar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        javax.swing.GroupLayout DeskUsuarioLayout = new javax.swing.GroupLayout(DeskUsuario);
        DeskUsuario.setLayout(DeskUsuarioLayout);
        DeskUsuarioLayout.setHorizontalGroup(
            DeskUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        DeskUsuarioLayout.setVerticalGroup(
            DeskUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuarios");

        MniUsuariosAdd.setText("Agregar Usuario");
        MniUsuariosAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniUsuariosAddActionPerformed(evt);
            }
        });
        jMenu1.add(MniUsuariosAdd);

        MniUsuariosMod.setText("Modificar Usuario");
        MniUsuariosMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniUsuariosModActionPerformed(evt);
            }
        });
        jMenu1.add(MniUsuariosMod);

        MnuUsuarios.add(jMenu1);

        jMenu2.setText("Navegar");

        MniRegresar.setText("Regresar");
        MniRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MniRegresarActionPerformed(evt);
            }
        });
        jMenu2.add(MniRegresar);

        MnuUsuarios.add(jMenu2);

        setJMenuBar(MnuUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskUsuario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DeskUsuario)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MniUsuariosAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniUsuariosAddActionPerformed
        ifrmUsuarioAdd AddVentana = new ifrmUsuarioAdd(this, userList);
        this.DeskUsuario.add(AddVentana);
        AddVentana.show();
    }//GEN-LAST:event_MniUsuariosAddActionPerformed

    private void MniRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniRegresarActionPerformed
        main.setVisible(true);
        dispose();   
    }//GEN-LAST:event_MniRegresarActionPerformed

    private void MniUsuariosModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MniUsuariosModActionPerformed
        ifrmUsuarioMod ModVentana = new ifrmUsuarioMod(this, userList);
        this.DeskUsuario.add(ModVentana);
        ModVentana.show();
    }//GEN-LAST:event_MniUsuariosModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DeskUsuario;
    private javax.swing.JMenuItem MniRegresar;
    private javax.swing.JMenuItem MniUsuariosAdd;
    private javax.swing.JMenuItem MniUsuariosMod;
    private javax.swing.JMenuBar MnuUsuarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    // End of variables declaration//GEN-END:variables
}
