package proyectofinal;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author lcarv
 */
public class ifrmUsuarioMod extends javax.swing.JInternalFrame {

    frmUsuario2 usuarioVentana;
    
    public ifrmUsuarioMod(frmUsuario2 usuarioVentana) {
        initComponents();
        this.usuarioVentana = usuarioVentana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        cbxBox = new javax.swing.JComboBox<>();
        lblAcceso = new javax.swing.JLabel();
        rbtCajero = new javax.swing.JRadioButton();
        rbtAdmin = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        lblTitle.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Modificar usuarios");

        lblUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuario.setText("Nombre de Usuario:");

        lblcontraseña.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblcontraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblcontraseña.setText("Contraseña:");

        txtPass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtPass.setEnabled(false);

        cbxBox.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbxBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBoxActionPerformed(evt);
            }
        });

        lblAcceso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblAcceso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAcceso.setText("Nivel de Acceso:");

        rbtCajero.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtCajero.setText("Cajero");
        rbtCajero.setEnabled(false);
        rbtCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCajeroActionPerformed(evt);
            }
        });

        rbtAdmin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rbtAdmin.setText("Administrador");
        rbtAdmin.setEnabled(false);

        jButton1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton1.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblcontraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAcceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtCajero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtAdmin)
                                .addGap(0, 61, Short.MAX_VALUE))
                            .addComponent(cbxBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPass)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(cbxBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontraseña)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAcceso)
                    .addComponent(rbtCajero)
                    .addComponent(rbtAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtCajeroActionPerformed

    private void cbxBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAcceso;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JRadioButton rbtAdmin;
    private javax.swing.JRadioButton rbtCajero;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
